export const genomeDetailsTexts = {
    genome: "Genome",
    download: "Download",
    genomeSize: "Genome size",
    completeness: "Completeness",
    contamination: "Contamination",
    gcContent: "GC content",
    totalCodingSequences: "Total coding sequences",
    numberOfGenes: "Number of genes",
    called: "Called",
    mapped: "Mapped",
    contigComposition: "Contig composition",
    nContigs: "Number of contigs",
    contigN50: "Contig N50",
    additionalNotes: "Additional Notes",
    classification: "Classification",
    msaPercent: "MSA percent",
    redValue: "RED value",
    proportionGenesRetainedInMajorClades: "Proportion of genes retained in major clades",
    genesRetainedIndex: "Genes retained index",
    cladeSeparationScore: "Clade separation score",
    contaminationPortion: "Contamination portion",
    nEffectiveSurplusClades: "Number of effective surplus clades",
    meanHitIdentity: "Mean hit identity",
    referenceRepresentationScore: "Reference representation score",
    passGNUC: "Pass.GNUC",
    trnaNumber: "Number of tRNA",
    s16Number: "Number of 16S",
    s5Number: "Number of 5S",
    s23Number: "Number of 23S",
    expand: "Expand",
    classificationLabel: "Classification",
    showTableLabel: "Show table",
    hideTableLabel: "Hide table",
    domain: "Domain",
    phylum: "Phylum",
    class: "Class",
    order: "Order",
    family: "Family",
    genus: "Genus",
    species: "Species",
}
